### ISSUE TITLE
Couldn't make project for debian

### ISSUE THREAD

**Issue by alexandr-kriptonov** [MiT-Ufa/Slacker#1]
I can't make this project in debian.
I Installed Qt4.8.6, pulling project and try to "make all".
I'm getting this error:

```
/home/shepilov/repos/Slacker/asemantools/asemannativenotification.cpp:7: ошибка: field 'items' has incomplete type 'QHash<unsigned int, AsemanNativeNotificationItem*>'
     QHash<uint, AsemanNativeNotificationItem*> items;
                                                ^
```

Can you help?

**Comment by Snegovikufa** [comment]
I don't think that you can use Qt 4.8.6, because I create Slacker for Qt 5.4, where webkit notifications are supported.

**Comment by alexandr-kriptonov** [comment]
Ty, i try to install Qt5.4 and confirm you.

**Comment by Snegovikufa** [comment]
Also, there was the bug fixed in Qt 5.4.1 when pasting with CTRL+V in russian keyboard layout.

**Comment by alexandr-kriptonov** [comment]
It's great :+1:

**Comment by alexandr-kriptonov** [comment]
I installed Qt5.4 and again getting a error. See screeshots for more information.
http://imgur.com/rsq2tU8
http://imgur.com/1KZWrY9
http://imgur.com/6mYIoh5
Can you give me build options for command line when you use?

**Comment by Snegovikufa** [comment]
I just build app from QtCreator, but it should be like:

```
/home/shepilov/Qt/5.4/gcc_64/bin/qmake
make
```

**Comment by alexandr-kriptonov** [comment]
Thank you. It's work for me!
