### ISSUE TITLE
Optional hiding instead of closing by window close

### ISSUE THREAD

**Issue by navrocky** [MiT-Ufa/Slacker#3]

**Comment by olfway** [comment]
It seems you forgot to initialise "userWantsToClose" variable, i guess it should be "false" on start.
Also it would be better to use word "Exit" instead of "Close" in tray menu, because it actually exit.

And could you make "hideOnClose=true" by default, pls?

**Comment by navrocky** [comment]
pls look at my pull request https://github.com/Snegovikufa/TeamWords/pull/6
